### PR TITLE
feat: add execution_project configuration

### PR DESCRIPTION
**Pull request by maztohir**
Close https://github.com/odpf/transformers/issues/8

### CODE REVIEW

**Comment by kushsharma** [comment]
@maztohir sorry for the delayed review, can you also update `TaskConfigFromFile`? It's in the same file as `task/bq2bq/executor/bumblebee/config.py`. The rest of the changes looks good.

**Review by kushsharma — CHANGES_REQUESTED** [review]
@maztohir sorry for the delayed review, can you also update `TaskConfigFromFile`? It's in the same file as `task/bq2bq/executor/bumblebee/config.py`. The rest of the changes looks good.

**Comment by maztohir** [comment]
> @maztohir sorry for the delayed review, can you also update `TaskConfigFromFile`? It's in the same file as `task/bq2bq/executor/bumblebee/config.py`. The rest of the changes looks good.

Done added on this commit @kushsharma  https://github.com/odpf/transformers/pull/9/commits/77be3eb920a099e4efdbb3347a6520fd8c50c795 Thanks!

**Comment by kushsharma** [comment]
LGTM

**Pull request merged**
