### PR TITLE
fix: update entrypoint for optimus v0.2.1-rc.1

### PR DESCRIPTION
**Pull request by deryrahman**
- [x] remove `--with-server` flag when execute optimus version
- [x] rename `--project` to `--project-name`

### CODE REVIEW

**Comment by deryrahman** [comment]
follow up from changes https://github.com/odpf/optimus/pull/274

**Comment by ravisuhag** [comment]
@deryrahman IMO, project is more user friendly than project-name. WDYT?

**Comment by deryrahman** [comment]
@ravisuhag yes, but `--project-name` is also convenient. As of now, flags-to-override-config follows the conventions from config structure. so, the config:
```
project:
    name:
```
will be match with flag `--project-name`. Making it to `--project` requires effort, since the flags is automapped by flags-to-config bindings

**Comment by ravisuhag** [comment]
> @ravisuhag yes, but I think `--project-name` is also convenient. As of now, flags-to-override-config follows the conventions from config structure. so, the config:
> 
> ```
> project:
>     name:
> ```
> 
> will be match with flag `--project-name`. Making it to `--project` requires effort, since the flags is automapped by flags-to-config bindings

@deryrahman User experience is more important than effort IMO. Also, it was already `project`, so why are changing it now?

**Comment by deryrahman** [comment]
@ravisuhag noted, agree, new lesson for me. Actually, we change it to make it consistent with convention in config structure. But, sure, I think we can provide flag `--project` back(?) wdyt @sravankorumilli

**Pull request merged**
